# Issueのテストに使用していたCI
# 実運用には使いません
name: Close Issue CI

on:
  # push: 
  #   branches: 
  #     - feat/closeUnuseIssue
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm ci

      - name: Issue Control
        run: node .github/scripts/create-issue.js
        env: 
          GITHUB_TOKEN: ${{ secrets.BLC_ACCESS_TOKEN }}
          TARGET_REPO: ${{ secrets.BLOG_REPOSITORY }}
          CURRENT_DATE: '2021-10-18'
