name: Create Issue CI

on:
  push: 
    branches:
      - feature/createIssue
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm ci

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(TZ=Asia/Tokyo date +'%Y-%m-%d')"

      - name: Create Issue
        run: node .github/scripts/create-issue.js
        env: 
          GITHUB_TOKEN: ${{ secrets.BLC_ACCESS_TOKEN }}
          TARGET_REPO: ${{ secrets.BLOG_REPOSITORY }}
          CURRENT_DATE: ${{ steps.date.outputs.date }}
