# リンクチェックを実行するCI
name: Link check CI

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Gitの初期設定
      - name: git setting
        run: |
          git config --local user.email ${{ secrets.REPOSITORY_OWNER_EMAIL }}
          git config --local user.name ${{ github.repository_owner }}
      
      # Node.js セットアップ
      # LTSの最新は14系なのでとりあえずそれで指定
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      # 必要なパッケージのインストール
      - name: Install package
        run: npm install broken-link-checker -g

      # 実行テスト
      - name: Print help and version
        run: |
          blc --help
          blc --version

      # 結果用ファイル名の生成
      - name: Generate result filename
        id: filename
        run: |
          echo "::set-output name=result::result-$(date '+%Y_%m_%d_%H_%M_%S')"

      # 出力テスト
      - name: Print filename
        run: |
          echo ${{ steps.filename.outputs.result }}

      # リンクチェック実行
      - name: Exec link-check
        run: |
          while read url
            do
              echo "$url"
            done < post-list.txt
