name: Actionlint CI
on: 
  push:
    branches:
      - master
    paths:
      - '.github/**/*.yml'
  workflow_dispatch:
jobs:
  exec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run ActionLint
        shell: bash
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color -ignore 'SC2002' -ignore 'SC2129' -ignore 'SC2143'
