name: Posts CI

on:
  push:
    branches: [ Jpsern-patch-1 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Gitの初期設定
      - name: git setting
        run: |        
          git config --local user.email ${{ secrets.REPOSITORY_OWNER_EMAIL }}
          git config --local user.name ${{ github.repository_owner }}
          git checkout Jpsern-patch-1
          git branch

      # サイトマップからURLリスト作成
      - name: create posts.txt
        run: |
          curl -fsSL https://jpsern.com/post-sitemap.xml |  grep "<loc" | sed -e "s/^.*<loc>//g;s/<\/loc>.*$//g" > post-list.txt

      # 差分の有無を確認する
      - name: check diffs
        id: diffs
        run: |
          git add posts.txt
          echo "::set-output name=count::$(git diff --name-only | wc -l)"

      # commit, push 
#      - name: commit file and push
#        run: |        
#          git add post-list.txt
#          git commit -m 'Update posts.txt'
#          git push
