# リンクチェック対象リストを作成するCI
name: Post list CI

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FILENAME: post-list.txt

    steps:
      - uses: actions/checkout@v2

      # Gitの初期設定
      - name: Git setting
        run: sh ./scripts/git_settings.sh
        env:
          REPOSITORY_OWNER: ${{ github.repository_owner }}
          REPOSITORY_OWNER_EMAIL: ${{ secrets.REPOSITORY_OWNER_EMAIL }}

      # サイトマップからURLリスト作成
      - name: Create URL list
        run: |
          curl -fsSL https://jpsern.com/post-sitemap.xml |  grep "<loc" | sed -e "s/^.*<loc>//g;s/<\/loc>.*$//g" > $FILENAME

      # 差分の有無を確認する
      - name: Check diffs
        id: diffs
        run: |
          git add -N $FILENAME
          echo "::set-output name=count::$(git diff --name-only | wc -l)"

      # カウント出力テスト
      - name: Print diffs count
        run: |
          echo ${{ steps.diffs.outputs.count }}

      # 差分カウントが0以上ならコミットしてプッシュする
      - name: Commit file and push
        run: |
          git add $FILENAME
          git commit -m "Update $FILENAME"
          git push
        if: steps.diffs.outputs.count > 0
